Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -24,69 +24,12 @@ jobs:
     - name: Build
       run: dotnet build --no-restore
     - name: Test
-      run: dotnet test --no-build --verbosity normal
+      run: dotnet test --no-build --logger "trx;LogFileName=test-results.trx"
       
-    - name: Test Reporter
+    - name: Test Report
       uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
       with:
-
-        # Name or regex of artifact containing test results
-        # Regular expression must be enclosed in '/'.
-        # Values from captured groups will replace occurrences of $N in report name.
-        # Example:
-        #   artifact: /test-results-(.*)/
-        #   name: 'Test report $1'
-        #   -> Artifact 'test-result-ubuntu' would create report 'Test report ubuntu'
-        artifact: ''
-
-        # Name of the Check Run which will be created
-        name: ''
-
-        # Coma separated list of paths to test results
-        # Supports wildcards via [fast-glob](https://github.com/mrmlnc/fast-glob)
-        # All matched result files must be of the same format
-        path: ''
-
-        # The fast-glob library that is internally used interprets backslashes as escape characters.
-        # If enabled, all backslashes in provided path will be replaced by forward slashes and act as directory separators.
-        # It might be useful when path input variable is composed dynamically from existing directory paths on Windows.
-        path-replace-backslashes: 'false'
-
-        # Format of test results. Supported options:
-        #   dart-json
-        #   dotnet-trx
-        #   flutter-json
-        #   java-junit
-        #   jest-junit
-        #   mocha-json
-        reporter: ''
-
-        # Allows you to generate only the summary.
-        # If enabled, the report will contain a table listing each test results file and the number of passed, failed, and skipped tests.
-        # Detailed listing of test suites and test cases will be skipped.
-        only-summary: 'false'
-
-        # Limits which test suites are listed:
-        #   all
-        #   failed
-        list-suites: 'all'
-
-        # Limits which test cases are listed:
-        #   all
-        #   failed
-        #   none
-        list-tests: 'all'
-
-        # Limits number of created annotations with error message and stack trace captured during test execution.
-        # Must be less or equal to 50.
-        max-annotations: '10'
-
-        # Set action as failed if test report contains any failed test
-        fail-on-error: 'true'
-
-        # Relative path under $GITHUB_WORKSPACE where the repository was checked out.
-        working-directory: ''
-
-        # Personal access token used to interact with Github API
-        # Default: ${{ github.token }}
-        token: ''
+        name: Unit Test Results            # Name of the check run which will be created
+        path: DemoWebApi.Test\TestResults\test-results.trx    # Path to test results
+        reporter: dotnet-trx        # Format of test results
